loki:
  auth_enabled: false

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m

  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3

  query_scheduler:
    max_outstanding_requests_per_tenant: 10000

write:
  replicas: 2

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"

read:
  replicas: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"

gateway:
  enabled: true
  replicas: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki.local

minio:
  enabled: true
  replicas: 1
  # Minio requires 2 to 16 drives for erasure code (drivesPerNode * replicas)
  # https://docs.min.io/docs/minio-erasure-code-quickstart-guide
  # Since we only have 1 replica, that means 2 drives must be used.
  drivesPerNode: 2
  rootUser: enterprise-logs
  rootPassword: supersecret
  buckets:
    - name: chunks
      policy: none
      purge: false
    - name: ruler
      policy: none
      purge: false
    - name: admin
      policy: none
      purge: false
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi