loki:
  auth_enabled: false

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: http://10.96.192.224:9000
      accessKeyId: loki
      secretAccessKey: loki1234
      s3ForcePathStyle: true
      insecure: true

  query_scheduler:
    max_outstanding_requests_per_tenant: 10000

write:
  replicas: 2

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"

read:
  replicas: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"

gateway:
  enabled: true
  replicas: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki.local
