alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.local
    tls:
      - secretName: prometheus-alerts-tls
        hosts:
          - alertmanager.local


server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
       - prometheus.local
    tls:
       - secretName: prometheus-server-tls
         hosts:
           - prometheus.local
  replicaCount: 1
  statefulSet:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  retention: "15d"

pushgateway:
  ingress:
    enabled: true
    hosts:
      - pushgateway.local
    tls:
      - secretName: prometheus-alerts-tls
        hosts:
          - pushgateway.local
