replicas: 3

tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

metrics:
  enabled: true

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack

args:
- --kubelet-insecure-tls
